version: "3.8"

services:
  db:
    image: mysql:8.4
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: .env

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "4000:3000"

volumes:
  db_data:
